package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	"errors"

	"github.com/mikalai2006/geoinfo-api/graph/generated"
	"github.com/mikalai2006/geoinfo-api/graph/model"
	"github.com/mikalai2006/geoinfo-api/internal/domain"
	"github.com/mikalai2006/geoinfo-api/internal/repository"
	"github.com/mikalai2006/geoinfo-api/internal/utils"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

// ID is the resolver for the id field.
func (r *amenityGroupResolver) ID(ctx context.Context, obj *model.AmenityGroup) (string, error) {
	return obj.ID.Hex(), nil
}

// UserID is the resolver for the userId field.
func (r *amenityGroupResolver) UserID(ctx context.Context, obj *model.AmenityGroup) (string, error) {
	return obj.UserID.Hex(), nil
}

// Props is the resolver for the props field.
func (r *amenityGroupResolver) Props(ctx context.Context, obj *model.AmenityGroup) (any, error) {
	return obj.Props, nil
}

// AmenityGroups is the resolver for the amenityGroups field.
func (r *queryResolver) AmenityGroups(ctx context.Context, limit *int, skip *int, input *model.FetchAmenityGroup) (*model.PaginationAmenityGroup, error) {
	var results *model.PaginationAmenityGroup
	gc, err := utils.GinContextFromContext(ctx)
	if err != nil {
		return results, err
	}
	lang := gc.MustGet("i18nLocale").(string)

	allItems, err := r.Repo.AmenityGroup.GqlGetAmenityGroups(domain.RequestParams{
		Options: domain.Options{Limit: int64(*limit), Skip: int64(*skip)},
		Filter:  bson.D{},
		Lang:    lang,
	})
	if err != nil {
		return results, err
	}

	items := make([]*model.AmenityGroup, len(allItems))
	for i, _ := range allItems {

		items[i] = allItems[i]
	}

	count, err := r.DB.Collection(repository.TblAmenityGroup).CountDocuments(ctx, bson.M{})
	if err != nil {
		return results, err
	}
	countInt := int(count)

	results = &model.PaginationAmenityGroup{
		Data:  items,
		Total: &countInt,
	}
	if skip != nil {
		results.Skip = skip
	}
	if limit != nil {
		results.Limit = limit
	}

	return results, nil
}

// AmenityGroup is the resolver for the amenityGroup field.
func (r *queryResolver) AmenityGroup(ctx context.Context, id *string) (*model.AmenityGroup, error) {
	var result *model.AmenityGroup
	gc, err := utils.GinContextFromContext(ctx)
	if err != nil {
		return result, err
	}
	lang := gc.MustGet("i18nLocale").(string)

	filter := bson.D{}
	if id != nil {
		userIDPrimitive, err := primitive.ObjectIDFromHex(*id)
		if err != nil {
			return result, err
		}

		filter = append(filter, bson.E{"_id", userIDPrimitive})
	}

	// if err := r.DB.Collection(repository.TblAmenity).FindOne(ctx, filter).Decode(&result); err != nil {
	// 	if errors.Is(err, mongo.ErrNoDocuments) {
	// 		return result, model.ErrAmenityNotFound
	// 	}
	// 	return result, err
	// }
	allItems, err := r.Repo.AmenityGroup.GqlGetAmenityGroups(domain.RequestParams{
		Options: domain.Options{Limit: 1},
		Filter:  bson.D{},
		Lang:    lang,
	})
	if errors.Is(err, mongo.ErrNoDocuments) {
		return result, model.ErrAmenityGroupNotFound
	}

	result = allItems[0]

	return result, nil
}

// AmenityGroup returns generated.AmenityGroupResolver implementation.
func (r *Resolver) AmenityGroup() generated.AmenityGroupResolver { return &amenityGroupResolver{r} }

type amenityGroupResolver struct{ *Resolver }
