package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	"errors"

	"github.com/mikalai2006/geoinfo-api/graph/generated"
	"github.com/mikalai2006/geoinfo-api/graph/model"
	"github.com/mikalai2006/geoinfo-api/internal/domain"
	"github.com/mikalai2006/geoinfo-api/internal/repository"
	"github.com/mikalai2006/geoinfo-api/internal/utils"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

// Tagopts is the resolver for the tagopts field.
func (r *queryResolver) Tagopts(ctx context.Context, first *int, after *string, limit *int, skip *int, input *model.FetchTagopt) (*model.PaginationTagopt, error) {
	var results *model.PaginationTagopt

	allItems, err := r.Repo.Tagopt.GqlGetTagopts(domain.RequestParams{
		Options: domain.Options{Limit: int64(*limit)},
		Filter:  bson.D{},
	})
	if err != nil {
		return results, err
	}

	items := make([]*model.Tagopt, len(allItems))
	for i, _ := range allItems {

		items[i] = allItems[i]
	}

	count, err := r.DB.Collection(repository.TblTagopt).CountDocuments(ctx, bson.M{})
	if err != nil {
		return results, err
	}
	countInt := int(count)

	results = &model.PaginationTagopt{
		Data:  items,
		Total: &countInt,
		Limit: limit,
		Skip:  skip,
	}

	return results, nil
}

// Tagopt is the resolver for the tagopt field.
func (r *queryResolver) Tagopt(ctx context.Context, input *model.FetchTagopt) (*model.Tagopt, error) {
	var result *model.Tagopt

	filter := bson.D{}
	if input.ID != nil {
		userIDPrimitive, err := primitive.ObjectIDFromHex(*input.ID)
		if err != nil {
			return result, err
		}

		filter = append(filter, bson.E{"_id", userIDPrimitive})
	}

	if err := r.DB.Collection(repository.TblTagopt).FindOne(ctx, filter).Decode(&result); err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return result, model.ErrTagOptNotFound
		}
		return result, err
	}
	return result, nil
}

// ID is the resolver for the _id field.
func (r *tagoptResolver) ID(ctx context.Context, obj *model.Tagopt) (string, error) {
	return obj.ID.Hex(), nil
}

// UserID is the resolver for the userId field.
func (r *tagoptResolver) UserID(ctx context.Context, obj *model.Tagopt) (string, error) {
	return obj.UserID.Hex(), nil
}

// TagID is the resolver for the tagId field.
func (r *tagoptResolver) TagID(ctx context.Context, obj *model.Tagopt) (string, error) {
	return obj.TagID.Hex(), nil
}

// Props is the resolver for the props field.
func (r *tagoptResolver) Props(ctx context.Context, obj *model.Tagopt) (any, error) {
	return obj.Props, nil
}

// User is the resolver for the user field.
func (r *tagoptResolver) User(ctx context.Context, obj *model.Tagopt) (*model.User, error) {
	var result *model.User
	gc, err := utils.GinContextFromContext(ctx)
	if err != nil {
		return result, err
	}
	lang := gc.MustGet("i18nLocale").(string)

	filter := bson.D{}
	filter = append(filter, bson.E{"_id", obj.UserID})

	allItems, err := r.Repo.User.GqlGetUsers(domain.RequestParams{
		Options: domain.Options{Limit: 1, Skip: 0},
		Filter:  filter,
		Lang:    lang,
	})
	if err != nil {
		return result, err
	}

	if len(allItems) > 0 {
		result = allItems[0]
	}

	return result, nil
}

// Tagopt returns generated.TagoptResolver implementation.
func (r *Resolver) Tagopt() generated.TagoptResolver { return &tagoptResolver{r} }

type tagoptResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *tagoptResolver) CreatedAt(ctx context.Context, obj *model.Tagopt) (string, error) {
	return obj.CreatedAt.String(), nil
}
func (r *tagoptResolver) UpdatedAt(ctx context.Context, obj *model.Tagopt) (string, error) {
	return obj.UpdatedAt.String(), nil
}
